--- #YAML:1.0
name:               DJabberd
version:            0.85
abstract:           scalable, extensible Jabber/XMPP server.
author:
    - Brad Fitzpatrick <brad@danga.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Danga::Socket:        1.51
    Digest::HMAC_SHA1:    0
    Log::Log4perl:        0
    Net::DNS:             0.48
    Net::SSLeay:          0
    Unicode::Stringprep:  0
    XML::LibXML:          1.7
    XML::LibXML::SAX:     0
    XML::SAX:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
